### ISSUE TITLE
Copy mechanism

### ISSUE THREAD

**Issue by dishavarshney082** [lizekang/ITDD#13]
Have you tried implementing  copy mechanism ( Pointer Generator) with your architecture? If yes how was the performance?

**Comment by lizekang** [comment]
No. But I tried copy mechanism in other tasks. In my opinion, I think the copy mechanism will bring just a little improvement. You can have a try.

**Comment by dishavarshney082** [comment]
I was trying copy mechanism but got stuck in understanding the purpose of variables 'src_map' and 'alignments'? Do you have any idea about the same?

**Comment by dishavarshney082** [comment]
Also, have you used pretrained models like GPT-2 to train the models?
