### ISSUE TITLE
Could your publish your code for the processed data？

### ISSUE THREAD

**Issue by ChuanMeng** [lizekang/ITDD#3]
I would appreciate it if you could share the code for the the processed data, thanks!

Or could you explain how you do that? For example, what NLP tool did you use? Spacy or nltk?; what  is the meaning of "\&quot;", "\&lt; SEP \&gt;" in kowledge and context? and so on. 
I hope you can give a detailed explanation.

**Comment by lizekang** [comment]
We use the NLP tools in the OpenNMT-py. You can see the instructions in http://opennmt.net/OpenNMT-py/extended.html. We use tools/tokenizer.perl as tokenizer. 
""" will be "&quot;" after tokenizing and "<SEP>" will be "&lt; SEP &gt;". 
And we use <SEP> to separate multi-turn context.

**Comment by ChuanMeng** [comment]
Thank you.
I understand the function of  "< SEP >". But why you convert """ to "\&quot;", beacuse the tokenizer.perl?

**Comment by lizekang** [comment]
Yes, tokenizer.perl convert """ to "&quot;".
