### ISSUE TITLE
About the setting n_gpu

### ISSUE THREAD

**Issue by iAlexKai** [lizekang/ITDD#6]
<img width="691" alt="image" src="https://user-images.githubusercontent.com/17684040/64057078-42bd1b80-cbcb-11e9-9106-4f5b88e3aa37.png">
Here, in onmt/trainer.py, if n_gpu = 1, and the gpu_rank in my config is not 0,then I can never get into this if, I wonder if this is a bug?

**Comment by lizekang** [comment]
Please refer to OpenNMT-py documentation.
