### ISSUE TITLE
no knowledge base with some utterances

### ISSUE THREAD

**Issue by dishavarshney082** [lizekang/ITDD#8]
If some dataset does not contain knowledge base for every utterance will the model work fo that dataset too?

**Comment by lizekang** [comment]
Maybe. If there is knowledge for the whole dialog, I think it will work. You can have a try.

**Comment by dishavarshney082** [comment]
Yeah Sure i'll try. Also I wanted to ask why there is one extra knowledge base given in input files after giving knowledge base for each utterance.

**Comment by dishavarshney082** [comment]
Also can the code handle non conversational inputs?
