### ISSUE TITLE
output from both the first decoder and second decoder are same

### ISSUE THREAD

**Issue by dishavarshney082** [lizekang/ITDD#9]
While translating I saw that output from both the decoders are coming exactly the same. Is it because I'm using a different dataset ?

**Comment by lizekang** [comment]
Which dataset are you using? If the dataset is too easy, the output from the first decoder and the second decoder may be the same.

**Comment by dishavarshney082** [comment]
I'm using the topical chat dataset (https://m.media-amazon.com/images/G/01/amazon.jobs/3079_Paper._CB1565131710_.pdf)

**Comment by dishavarshney082** [comment]
Also, during translation I saw that after returning the outputs from the first decoder it is not making predictions using the second decoder since  
           if all((b.done() for b in beam)):
                break
this part is returning true and it comes out of the for loop.
Can you explain this part ?

**Comment by dishavarshney082** [comment]
Also, doesn't getting same output means it is not able to use the given knowledge base properly?

**Comment by lizekang** [comment]
> Also, during translation I saw that after returning the outputs from the first decoder it is not making predictions using the second decoder since
> if all((b.done() for b in beam)):
> break
> this part is returning true and it comes out of the for loop.
> Can you explain this part ?

I didn't meet this issue in my experiments. I will check it after a while.

**Comment by lizekang** [comment]
> Also, doesn't getting same output means it is not able to use the given knowledge base properly?

Doesn't getting the same output means it's able to use the given knowledge base in the second decoding process. You can see the comparison between the first decoder results and the second decoder results, which is presented in the paper.

**Comment by malongxuan** [comment]
> Also, doesn't getting same output means it is not able to use the given knowledge base properly?
> 
> Doesn't getting the same output means it's able to use the given knowledge base in the second decoding process. You can see the comparison between the first decoder results and the second decoder results, which is presented in the paper.

We encounter the same "first decoder equals second" problem when using the CMUDoG dataset. We test several different data scales but the problem remains, it seems that the second decoder only performs as a PPL decliner.
